//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAndLoadTestProject {
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    
    
    [DeploymentItem("webandloadtestproject\\Book1.csv")]
    [DataSource("DataSource1", "Microsoft.VisualStudio.TestTools.DataSource.CSV", "|DataDirectory|\\Book1.csv", Microsoft.VisualStudio.TestTools.WebTesting.DataBindingAccessMethod.Sequential, Microsoft.VisualStudio.TestTools.WebTesting.DataBindingSelectColumns.SelectOnlyBoundColumns, "Book1#csv")]
    [DeploymentItem("webandloadtestproject\\Resources\\Login.csv")]
    [DataSource("Login", "Microsoft.VisualStudio.TestTools.DataSource.CSV", "|DataDirectory|\\Resources\\Login.csv", Microsoft.VisualStudio.TestTools.WebTesting.DataBindingAccessMethod.Sequential, Microsoft.VisualStudio.TestTools.WebTesting.DataBindingSelectColumns.SelectOnlyBoundColumns, "Login#csv")]
    [DataBinding("DataSource1", "Book1#csv", "ï»¿email", "DataSource1.Book1#csv.ï»¿email")]
    [DataBinding("DataSource1", "Book1#csv", "user", "DataSource1.Book1#csv.user")]
    public class autoConsultarBalanceCodedTemp : WebTest
    {
        
        public autoConsultarBalanceCodedTemp() {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }
        
        public override IEnumerator<WebTestRequest> GetRequestEnumerator() {
            WebTestRequest request1 = new WebTestRequest("http://localhost/");
            request1.Method = "POST";
            FormPostHttpBody request1Body = new FormPostHttpBody();
            request1Body.FormPostParameters.Add("Parameter1", this.Context["DataSource1.Book1#csv.ï»¿email"].ToString());
            request1Body.FormPostParameters.Add("Parameter2", this.Context["DataSource1.Book1#csv.user"].ToString());
            request1.Body = request1Body;
            yield return request1;
            request1 = null;
        }
    }
}
