//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAndLoadTestProject.TestCases.Coded
{
    using System;
    using System.Collections.Generic;
    using System.Text;
    using Microsoft.VisualStudio.TestTools.WebTesting;
    using PerformanceLibrary.Utils;
    using Microsoft.VisualStudio.TestTools.WebTesting.Rules;
    using PerformanceLibrary.ValidationRules;
    using PerformanceLibrary.Core;


    [DeploymentItem("webandloadtestproject\\Resources\\Movimientos.csv")]
    [DataSource("Movimientos", "Microsoft.VisualStudio.TestTools.DataSource.CSV", "|DataDirectory|\\Resources\\Movimientos.csv", Microsoft.VisualStudio.TestTools.WebTesting.DataBindingAccessMethod.Sequential, Microsoft.VisualStudio.TestTools.WebTesting.DataBindingSelectColumns.SelectOnlyBoundColumns, "Movimientos#csv")]
    [DataBinding("Movimientos", "Movimientos#csv", "currencyId", "Movimientos.Movimientos#csv.currencyId")]
    [DataBinding("Movimientos", "Movimientos#csv", "creditLineId", "Movimientos.Movimientos#csv.creditLineId")]
    [DataBinding("Movimientos", "Movimientos#csv", "cardId", "Movimientos.Movimientos#csv.cardId")]
    [DataBinding("Movimientos", "Movimientos#csv", "billingCycleId", "Movimientos.Movimientos#csv.billingCycleId")]
    [DataBinding("Movimientos", "Movimientos#csv", "billingPeriodId", "Movimientos.Movimientos#csv.billingPeriodId")]
    [DataBinding("Movimientos", "Movimientos#csv", "billingYear", "Movimientos.Movimientos#csv.billingYear")]
    [IncludeCodedWebTest("WebAndLoadTestProject.TestCases.GenerateGAMToken", "webandloadtestproject.dll")]
    public class autoMovimientosTarjetaCoded : WebTest
    {
        PropertyLoader propertyLoader = new PropertyLoader();

        public autoMovimientosTarjetaCoded()
        {
            this.PreAuthenticate = true;
            this.Proxy = "default";
        }

        public override IEnumerator<WebTestRequest> GetRequestEnumerator()
        {
            //Environment definition
            this.Context["NetEnvironment"] = propertyLoader.GetPropertyAUT("EnvironmentURL");

            #region ValidationRules

            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidateResponseUrl validationRule1 = new ValidateResponseUrl();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validationRule1.Validate);
            }
            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                ValidationRuleResponseTimeGoal validationRule2 = new ValidationRuleResponseTimeGoal();
                validationRule2.Tolerance = 0D;
                this.ValidateResponseOnPageComplete += new EventHandler<ValidationEventArgs>(validationRule2.Validate);
            }

            if ((this.Context.ValidationLevel >= Microsoft.VisualStudio.TestTools.WebTesting.ValidationLevel.Low))
            {
                HTTPResponseCode validateResponseCode = new HTTPResponseCode();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(validateResponseCode.Validate);
                Assert assertResponse = new Assert();
                this.ValidateResponse += new EventHandler<ValidationEventArgs>(assertResponse.Validate);
            }
            #endregion

            #region Dependent WebTest

            if (Base.AccessToken.Count < 1)
            {
                foreach (WebTestRequest wtr in IncludeWebTest("GenerateGAMToken", false)) { yield return wtr; }
            }

            #endregion

            string access_token = "";
            if (Base.AccessToken.Count > 0) { access_token = Base.AccessToken[0]; }

            string sBody = string.Format("{{\"token\":\"{0}\"," +
                "\"movParms\":{{\"currencyId\":{1},\"creditLineId\":{2},\"cardId\":\"{3}\",\"billingCycleId\":{4},\"billingPeriodId\":{5},\"billingYear\":{6}}}" +
                "}}", access_token,Convert.ToUInt32(this.Context["Movimientos.Movimientos#csv.currencyId"].ToString()), Convert.ToUInt32(this.Context["Movimientos.Movimientos#csv.creditLineId"].ToString()),
                StringManagement.CleanUpChar("'",this.Context["Movimientos.Movimientos#csv.cardId"].ToString()),Convert.ToUInt32(this.Context["Movimientos.Movimientos#csv.billingCycleId"].ToString()),
                Convert.ToUInt32(this.Context["Movimientos.Movimientos#csv.billingPeriodId"].ToString()),Convert.ToUInt32(this.Context["Movimientos.Movimientos#csv.billingYear"].ToString()));

            #region WebTest

            this.BeginTransaction("PH_NP_MovimientosTarjeta");
            WebTestRequest webRequest = new WebTestRequest(this.Context["NetEnvironment"].ToString() + "/phApp/rest/getMovimientosTarjetaPalacio");
            webRequest.ExpectedHttpStatusCode = 200;
            webRequest.Method = "POST";
            webRequest.Cache = false;
            //webRequest.ThinkTime = Base.GetThinkTime();
            webRequest.Headers.Add(new WebTestRequestHeader("Accept-Encoding", "gzip,deflate"));
            webRequest.Headers.Add(new WebTestRequestHeader("Content-type", "application/json"));
            webRequest.Headers.Add(new WebTestRequestHeader("Authorization", propertyLoader.GetPropertyAUT("OAuth")));
            //Request Body JSON
            StringHttpBody webRequestLoginBody = new StringHttpBody { BodyString = sBody, ContentType = "application/json", InsertByteOrderMark = false };
            webRequest.Body = webRequestLoginBody;
            yield return webRequest;
            webRequest = null;
            this.EndTransaction("PH_NP_MovimientosTarjeta");

            #endregion

            #region Validation Response

            #endregion


        }
    }
}
