//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilsLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Properties {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Properties() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UtilsLibrary.Resources.Properties", typeof(Properties).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CandidateId.
        /// </summary>
        internal static string data_CandidateId {
            get {
                return ResourceManager.GetString("data_CandidateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CandidateName.
        /// </summary>
        internal static string data_CandidateName {
            get {
                return ResourceManager.GetString("data_CandidateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CodeNumber.
        /// </summary>
        internal static string data_CodeNumber {
            get {
                return ResourceManager.GetString("data_CodeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomerNumber.
        /// </summary>
        internal static string data_CustomerNumber {
            get {
                return ResourceManager.GetString("data_CustomerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EstimateGuid.
        /// </summary>
        internal static string data_EstimateGuid {
            get {
                return ResourceManager.GetString("data_EstimateGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemGuid.
        /// </summary>
        internal static string data_ItemGuid {
            get {
                return ResourceManager.GetString("data_ItemGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectGuid.
        /// </summary>
        internal static string data_ProjectGuid {
            get {
                return ResourceManager.GetString("data_ProjectGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://selnavtst-johnsoncontrols.cs43.force.com/.
        /// </summary>
        internal static string EnvironmentURL {
            get {
                return ResourceManager.GetString("EnvironmentURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string JSONCodeBlockDisabled {
            get {
                return ResourceManager.GetString("JSONCodeBlockDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PerfTest_.
        /// </summary>
        internal static string ProjectNameTemplateConvention {
            get {
                return ResourceManager.GetString("ProjectNameTemplateConvention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string QAEnv {
            get {
                return ResourceManager.GetString("QAEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string RandomValues {
            get {
                return ResourceManager.GetString("RandomValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20681f1c-f319-495f-83ef-e4628e53ddbf.
        /// </summary>
        internal static string SessionToken {
            get {
                return ResourceManager.GetString("SessionToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string SOAPCodeBlockDisabled {
            get {
                return ResourceManager.GetString("SOAPCodeBlockDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UtilsLibrary\Resources\LoadTestData.xls.
        /// </summary>
        internal static string TestDataFile {
            get {
                return ResourceManager.GetString("TestDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baseline.
        /// </summary>
        internal static string TestDataSheet {
            get {
                return ResourceManager.GetString("TestDataSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string ThinkTime {
            get {
                return ResourceManager.GetString("ThinkTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jci.selnavtst.hn.
        /// </summary>
        internal static string UserDomain {
            get {
                return ResourceManager.GetString("UserDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noel.baca@jci.snmajor.qa.hn.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelNav201706!!.
        /// </summary>
        internal static string UserPassword {
            get {
                return ResourceManager.GetString("UserPassword", resourceCulture);
            }
        }
    }
}
